# (PART) INTRODUCTION TO GENERALISED LINEAR MODELS {-}

# Introduction

General Linear models predict the value of a normally distributed response from a linear combination of predictor variables.

The General*ised* Linear Model is an extension of the General Linear model for situations where the response variable does not follow the normal distribution. It generalises by allowing the linear model to be related to the response variable by a *link* function. 

When you have a single explanatory variable, that model is:

\begin{equation}
function(E(y_{i})=\beta_{0}+\beta_{1}X1_{i}
(\#eq:glm1)
\end{equation}

The response variable can come from one of a large family of distributions known as the Exponential family which includes the normal, Poisson, binomial and gamma distributions. 


estimates are on scale of the link function

antilog


## poisson

the maths, the parameters, the mean of the parameters

the link function


## binomial

## general form of r code

## general form of output

## model tests

fit

deviance

AIC




